name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read OS version
        run: cat /etc/os-release

      - name: Read System Config
        run: |
          lsmem | head -10
          lscpu | head -20

      - name: Hosted on ??
        run: sudo dmidecode -t system
